config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'products#index'
  get 'about' => 'pages#about'

  resources :products do
    resources :purchases, only: [:index, :new, :create]
  end

  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      resources :products, only: [:index, :show]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images
  belongs_to :brand

  has_paper_trail

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, presence: true
  # validates :images, presence: true

  has_many :purchases, dependent: :destroy
  has_many :users, through: :purchases
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  validates :address, presence: true
  validates :telephone, presence: true

  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :purchases
  has_many :products, through: :purchases
end

app/controllers/api/v1/products_controller.rb
module Api
  module V1
    class ProductsController < ActionController::Base
      def index
        render json: Product.all, status: :ok
      end

      def show
        render json: Product.find(params[:id]), status: :ok
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = 'Sobre nosotros'
    @content = 'Somos una empresa que lleva 38 años en el mercado.'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_paper_trail_whodunnit

    def index

    end

    def show
      @product = product
    end

    def new
      @product = Product.new
    end

    def edit
      @product = product
    end

    def create
      @product = Product.new(product_params)

      if @product.validate(params[:product])
        @product.save
        redirect_to @product
      else
        flash[:danger] = 'Los detalles del producto no son validos.'
        render :edit
      end
    end

    def update
      @product = product

      if @product.update product_params
        redirect_to @product
      else
        flash[:danger] = "El producto no pudo ser actualizado."
        render :edit
      end
    end

    def destroy
      @product = product
      @product.destroy

      redirect_to products_path
    end

    private
    def product
      @product ||= Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :brand_id, :discount, images: [])
    end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  def index
    @purchases = Purchase.all
  end

  def new
    @purchase = Purchase.new
    @product = Product.find(params["product_id"])
  end
  
  def create
    @product = Product.find(params["product_id"])

    @purchase = Purchase.new(
      address: params["purchase"]["address"],
      telephone: params["purchase"]["telephone"],
      product_price: @product.price,
      product_discount: @product.discount,
      product_id: params["product_id"],
      user_id: 1
    )

    if @purchase.save      
      flash[:success] = "La compra fue realizada exitosamente"
    else
      flash[:danger] = "La compra no pudo ser realizada"
    end

    redirect_to root_path
  end


  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:address, :telephone, :product_price, :product_discount, :product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def format_price price
    number_to_currency(price, separator: ',', delimiter: '.')
  end

  def crop_text text
    text.truncate(61)
  end

  def apply_discount price, discount
    discounted_price = price * (discount / 100.0)
    new_price = price - discounted_price
  end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
  def format_price price
    number_to_currency(price, separator: ',', delimiter: '.')
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <% key = key == 'notice' ? 'info' : key %>
  
  <div class="alert alert-<%= key %>">
    <%= value %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tienda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('watch.png') %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary mb-3">
      <%= link_to root_path, class: 'navbar-brand' do %>
        <%= image_tag 'watch.png', size: '30x30', class: 'd-inline-block align-top' %>
        Tienda de Relojes
      <% end %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to(products_path, class: 'nav-link') do %>
              Relojes
              <span class="sr-only">(current)</span>
            <% end %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Sobre nosotros</a>
          </li>
        </ul>

        <% if user_signed_in? %>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <button type="button" class="btn btn-outline-danger">
              Cerrar Sesión
            </button>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path do %>
            <button type="button" class="btn btn-outline-info">
              Iniciar sesión
            </button>
          <% end %>
        <% end %>
      </div>
    </nav>

    <%= render partial: 'layouts/flash' %>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/products/_form.html.erb
<%= form_with model: @product, local: true do |form| %>
  <div class="form-group">
    <%= form.label :name, 'Nombre' %>
    <%= form.text_field :name, class: "form-control", placeholder: 'Escriba el nombre del producto' %>
  </div>

  <div class="form-group">
    <%= form.label :brand_id, 'Marca' %>
    <%= form.collection_select :brand_id, Brand.all, :id, :name, { prompt: false }, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= form.label :description, 'Descripción' %>
    <%= form.text_area :description, class: "form-control", placeholder: 'Escriba una descripción del producto' %>
  </div>

  <div class="form-group">
    <%= form.label :price, 'Precio' %>
    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text">$</span>
      </div>
      <%= form.number_field :price, class: "form-control", placeholder: '999.999,00' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :discount, 'Descuento' %>
    <div class="input-group">
      <%= form.number_field :discount, class: "form-control", placeholder: '99' %>
      <div class="input-group-append">
        <span class="input-group-text">%</span>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :images, 'Imagenes' %>
    <%= form.file_field :images, multiple: true, class: 'form-control-file' %>
  </div>

  <% if @product.persisted? && @product.images.any? %>
    <% @product.images.each do |image| %>
      <%= image_tag image.variant(resize: '400x400')%>
    <% end %>
  <% end%>

  <div>
    <%= form.submit 'Guardar Producto', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<% if current_user.present? && current_user.admin %>
  <div class="row mb-5">
    <%= link_to new_product_path do %>
      <button type="button" class="btn btn-primary">
        <%= fa_icon 'plus-circle' %>
        Añadir Producto
      </button>
    <% end %>
  </div>
<% end %>

<div class="row">
  <% Product.all.each do |product| %>
    <div class="card bg-light mb-4 mr-4" style="width: 18rem">
      <% if product.discount && product.discount > 0 %>
        <span class="price-badge" aria-label="Descuento del producto actual">
          <%= product.discount %>% Descuento
        </span>
      <% end %>

      <%= link_to product do %>
        <%= image_tag product.images.first.variant(resize: '400x400'), class: 'card-img-top', alt: "Reloj: #{ product.brand.name }" %>
      <% end %>
      <div class="card-body">
        <h6 class="card-subtitle mb-2" aria-label="Marca del reloj"><%= product.brand.name.upcase %></h6>
        <h5 class="card-title" aria-label="Nombre del reloj"><%= product.name %></h5>

        <% if product.discount && product.discount > 0 %>
          <h6 class="card-subtitle mb-2 text-muted original-price" aria-label="Precio"><%= format_price product.price %></h6>
          <h6 class="card-subtitle mb-2 text-muted price-with-discount" aria-label="Precio con descuento"><%= format_price(apply_discount product.price, product.discount) %></h6>
        <% else %>
          <h6 class="card-subtitle mb-2 text-muted" aria-label="Precio total"><%= format_price product.price %></h6>
        <% end %>

        <p class="card-test" aria-label="Descripción del producto"><%= crop_text product.description %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<%= render 'form'%>

app/views/products/show.html.erb
<div class="container">
  <h6><%= @product.brand.name.upcase %></h6>
  <h1><%= @product.name %></h1>

  <% if current_user.present? && current_user.admin %>
    <button type="button" class="btn btn-outline-info mb-1" data-toggle="collapse" data-target="#history">
      Ver historial
    </button>
  <% end %>

  <div class="collapse mb-1" id="history">
    <div class="card card-body">
      <h6 class="card-title">Historial</h6>
      <ul class="list-group list-group-flush">
        <% @product.versions.each do |version| %>
          <li class="list-group-item">
            <% if version.whodunnit %>
              <%= User.find(version.whodunnit).email %>
            <% else %>
              Sistema
            <% end %>
            <strong><%= version.event.upcase %></strong>
            <%= version.created_at.localtime.to_date %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <% if @product.users.any? && current_user.present? && current_user.admin %>
    <div class="card mt-3 mb-5 p-3 shadow">
      <h2>Compras</h2>
      <ul class="purchases">
        <% @product.purchases.each do |purchase| %>
          <li class="purchases__element">
            <b>Comprador:</b> <%= purchase.user.email %><br>
            <b>Fecha:</b> <%= purchase.created_at %><br>
            <b>Dirección:</b> <%= purchase.address %><br>
            <b>Teléfono:</b> <%= purchase.telephone %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  
  <div id="carouselClocks"class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselClocks" data-slide-to="0" class="active"></li>
      <li data-target="#carouselClocks" data-slide-to="1"></li>
      <li data-target="#carouselClocks" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <% @product.images.each do |image| %>
        <div class="carousel-item <%= image == @product.images.first ? 'active' : '' %>">
          <%= image_tag image.variant(resize: '500x500'), class: 'd-block' %>
        </div>
      <% end %>
    </div>
  </div>

  <h2>Descripción</h2>
  <p><%= @product.description %></p>

  <h2>Precio</h2>
  <% if @product.discount && @product.discount > 0 %>
    <p class="original-price mb-0"><%= format_price @product.price %></p>
    <p class="price-with-discount"><%= format_price(apply_discount @product.price, @product.discount) %></p>
  <% else %>
    <p><%= format_price @product.price %></p>
  <% end %>

  <% if current_user.present? && current_user.admin %>
    <%= link_to @product, method: :delete do %>
      <button type="button" class="btn btn-danger">Eliminar</button>
    <% end %>
    <%= link_to edit_product_path do %>
      <button type="button" class="btn btn-info">Editar</button>
    <% end %>
  <% else %>
    <%= link_to new_product_purchase_path @product do%>
      <button type="button" class="btn btn-success">Comprar</button>
    <% end %>
  <% end %>
</div>

app/views/purchases/_form.html.erb
<%= form_with model: purchase, local: true, url: product_purchases_path do |form| %>
  <% if purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
        <% purchase.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h6><%= @product.brand.name.upcase %></h6>
  <h1><%= @product.name %></h1>
  <%= image_tag @product.images.first.variant(resize: '500x500') %>

  <div class="form-group">
    <%= form.label :product_price, "Precio" %>
    <%= form.text_field :product_price, class: 'form-control', value: format_price(@product.price), readonly: true %>
  </div>

  <div class="form-group">
    <%= form.label :product_discount, "Descuento" %>
    <%= form.text_field :product_discount, class: 'form-control', value: @product.discount.present? ? @product.discount : 0, readonly: true %>
  </div>

  <div class="form-group">
    <%= form.label :total_price, "Precio con descuento" %>
    <%= form.text_field :total_price, class: 'form-control', value: format_price(@product.discount.present? ? apply_discount(@product.price, @product.discount) : @product.price), readonly: true %>
  </div>

  <div class="form-group">
    <%= form.label :address, "Dirección" %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :telephone, "Teléfono" %>
    <%= form.text_field :telephone, class: 'form-control' %>
  </div>

  <div>
    <%= form.submit "Realizar compra", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/purchases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Purchases</h1>

<table>
  <thead>
    <tr>
      <th>Id user</th>
      <th>Id product</th>
      <th>Product price</th>
      <th>Product discount</th>
      <th>Address</th>
      <th>Telephone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.id_user %></td>
        <td><%= purchase.id_product %></td>
        <td><%= purchase.product_price %></td>
        <td><%= purchase.product_discount %></td>
        <td><%= purchase.address %></td>
        <td><%= purchase.telephone %></td>
        <td><%= link_to 'Show', purchase %></td>
        <td><%= link_to 'Edit', edit_purchase_path(purchase) %></td>
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase', new_purchase_path %>

app/views/purchases/new.html.erb
<%= render 'form', purchase: @purchase %>